/* 
 * openHAB REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.5
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using Openhab.Client.Client;
using Openhab.Client.Model;
using RestSharp;

namespace Openhab.Client.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IProfileTypesApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Gets all available profile types.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="acceptLanguage">Accept-Language (optional)</param>
        /// <param name="channelTypeUID">channel type filter (optional)</param>
        /// <param name="itemType">item type filter (optional)</param>
        /// <returns>List&lt;ProfileTypeDTO&gt;</returns>
        List<ProfileTypeDTO> GetAll (string acceptLanguage = null, string channelTypeUID = null, string itemType = null);

        /// <summary>
        /// Gets all available profile types.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="acceptLanguage">Accept-Language (optional)</param>
        /// <param name="channelTypeUID">channel type filter (optional)</param>
        /// <param name="itemType">item type filter (optional)</param>
        /// <returns>ApiResponse of List&lt;ProfileTypeDTO&gt;</returns>
        ApiResponse<List<ProfileTypeDTO>> GetAllWithHttpInfo (string acceptLanguage = null, string channelTypeUID = null, string itemType = null);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Gets all available profile types.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="acceptLanguage">Accept-Language (optional)</param>
        /// <param name="channelTypeUID">channel type filter (optional)</param>
        /// <param name="itemType">item type filter (optional)</param>
        /// <returns>Task of List&lt;ProfileTypeDTO&gt;</returns>
        System.Threading.Tasks.Task<List<ProfileTypeDTO>> GetAllAsync (string acceptLanguage = null, string channelTypeUID = null, string itemType = null);

        /// <summary>
        /// Gets all available profile types.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="acceptLanguage">Accept-Language (optional)</param>
        /// <param name="channelTypeUID">channel type filter (optional)</param>
        /// <param name="itemType">item type filter (optional)</param>
        /// <returns>Task of ApiResponse (List&lt;ProfileTypeDTO&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<ProfileTypeDTO>>> GetAllAsyncWithHttpInfo (string acceptLanguage = null, string channelTypeUID = null, string itemType = null);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class ProfileTypesApi : IProfileTypesApi
    {
        private ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="ProfileTypesApi"/> class.
        /// </summary>
        /// <returns></returns>
        public ProfileTypesApi(string basePath)
        {
            Configuration = new Configuration { BasePath = basePath };

            ExceptionFactory = Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ProfileTypesApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public ProfileTypesApi(Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                Configuration = Configuration.Default;
            else
                Configuration = configuration;

            ExceptionFactory = Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(string basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<string, string> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Gets all available profile types. 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="acceptLanguage">Accept-Language (optional)</param>
        /// <param name="channelTypeUID">channel type filter (optional)</param>
        /// <param name="itemType">item type filter (optional)</param>
        /// <returns>List&lt;ProfileTypeDTO&gt;</returns>
        public List<ProfileTypeDTO> GetAll (string acceptLanguage = null, string channelTypeUID = null, string itemType = null)
        {
             ApiResponse<List<ProfileTypeDTO>> localVarResponse = GetAllWithHttpInfo(acceptLanguage, channelTypeUID, itemType);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Gets all available profile types. 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="acceptLanguage">Accept-Language (optional)</param>
        /// <param name="channelTypeUID">channel type filter (optional)</param>
        /// <param name="itemType">item type filter (optional)</param>
        /// <returns>ApiResponse of List&lt;ProfileTypeDTO&gt;</returns>
        public ApiResponse< List<ProfileTypeDTO> > GetAllWithHttpInfo (string acceptLanguage = null, string channelTypeUID = null, string itemType = null)
        {

            var localVarPath = "/profile-types";
            var localVarPathParams = new Dictionary<string, string>();
            var localVarQueryParams = new List<KeyValuePair<string, string>>();
            var localVarHeaderParams = new Dictionary<string, string>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<string, string>();
            var localVarFileParams = new Dictionary<string, FileParameter>();
            object localVarPostBody = null;

            // to determine the Content-Type header
            string[] localVarHttpContentTypes = new string[] {
            };
            string localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            string[] localVarHttpHeaderAccepts = new string[] {
                "application/json"
            };
            string localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (channelTypeUID != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "channelTypeUID", channelTypeUID)); // query parameter
            if (itemType != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "itemType", itemType)); // query parameter
            if (acceptLanguage != null) localVarHeaderParams.Add("Accept-Language", Configuration.ApiClient.ParameterToString(acceptLanguage)); // header parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetAll", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<ProfileTypeDTO>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (List<ProfileTypeDTO>) Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<ProfileTypeDTO>)));
        }

        /// <summary>
        /// Gets all available profile types. 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="acceptLanguage">Accept-Language (optional)</param>
        /// <param name="channelTypeUID">channel type filter (optional)</param>
        /// <param name="itemType">item type filter (optional)</param>
        /// <returns>Task of List&lt;ProfileTypeDTO&gt;</returns>
        public async System.Threading.Tasks.Task<List<ProfileTypeDTO>> GetAllAsync (string acceptLanguage = null, string channelTypeUID = null, string itemType = null)
        {
             ApiResponse<List<ProfileTypeDTO>> localVarResponse = await GetAllAsyncWithHttpInfo(acceptLanguage, channelTypeUID, itemType);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Gets all available profile types. 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="acceptLanguage">Accept-Language (optional)</param>
        /// <param name="channelTypeUID">channel type filter (optional)</param>
        /// <param name="itemType">item type filter (optional)</param>
        /// <returns>Task of ApiResponse (List&lt;ProfileTypeDTO&gt;)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<List<ProfileTypeDTO>>> GetAllAsyncWithHttpInfo (string acceptLanguage = null, string channelTypeUID = null, string itemType = null)
        {

            var localVarPath = "/profile-types";
            var localVarPathParams = new Dictionary<string, string>();
            var localVarQueryParams = new List<KeyValuePair<string, string>>();
            var localVarHeaderParams = new Dictionary<string, string>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<string, string>();
            var localVarFileParams = new Dictionary<string, FileParameter>();
            object localVarPostBody = null;

            // to determine the Content-Type header
            string[] localVarHttpContentTypes = new string[] {
            };
            string localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            string[] localVarHttpHeaderAccepts = new string[] {
                "application/json"
            };
            string localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (channelTypeUID != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "channelTypeUID", channelTypeUID)); // query parameter
            if (itemType != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "itemType", itemType)); // query parameter
            if (acceptLanguage != null) localVarHeaderParams.Add("Accept-Language", Configuration.ApiClient.ParameterToString(acceptLanguage)); // header parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetAll", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<ProfileTypeDTO>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (List<ProfileTypeDTO>) Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<ProfileTypeDTO>)));
        }

    }
}
